#include "test_runner.h"
#include "profile.h"
using namespace std;

class Solution {
public:
	char findTheDifference(string & s, string & t) {
		//Runtime: 12 ms (28%)	Memory Usage: 6.5 MB (99.88%)
		map<char, int> m;
		for (auto c : s){
			m[c]++;
		}
		for (auto c : t){
			m[c]--;
		}
		for (auto c : m){
			if (c.second!=0)
				return c.first;
		}
		return s[0];
	}
};

int main() {
	
	{
		string input = "abcd";
		string second_input = "abcde";
		char answer = 'e';
		auto real_answer = Solution().findTheDifference(input, second_input);
		//cout<<real_answer<<" "<<answer<<endl<<endl;
		ASSERT_EQUAL(real_answer, answer);
	}
	
	cout<<endl<<"TESTS OK!"<<endl;
	
	return 0;
}

/*
Find the Difference

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/